# Generated by Django 4.1.7 on 2023-03-16 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=120, unique=True)),
                ('author', models.CharField(max_length=100)),
                ('price', models.PositiveIntegerField()),
                ('published_date', models.DateField(null=True)),
            ],
        ),
    ]
