# Generated by Django 4.1.7 on 2023-03-16 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='copies',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
