# Generated by Django 4.1.7 on 2023-03-16 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0002_books_copies'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='books',
            name='copies',
        ),
    ]
