# Generated by Django 4.1.7 on 2023-03-18 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0004_books_copies'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='image',
            field=models.ImageField(null=True, upload_to='images'),
        ),
    ]
